info:
  app:
    name: Concurrent/Async POC
    description: POC to show how to perform async requests to Star Wars API

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator

# Ribbon - Client load balancer config
swapi-client:
  ribbon:
    listOfServers: swapi.co:443

ribbon:
  IsSecure: true
  SecurePort: 443
  eureka:
   enabled: false

feign:
  client:
    config:
      swapi-client:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: false

# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

security:
  oauth2:
    resource:
      filter-order: 3
